const logData = [
  {
    date: '31-03-21',
    durationTrip: '0:35',
    meansOfTransport: 'car',
    routeTripFrom: 'Terneuzen - Vlissingen',
    routeTripTo: 'Terneuzen - Vlissingen',
    statusOfDay: 'car',
    weekNumber: 13,
  },
  {
    date: '31-03-21',
    durationTrip: '0:35',
    meansOfTransport: 'car',
    routeTripFrom: 'Vlissingen - Terneuzen',
    routeTripTo: 'Vlissingen - Terneuzen',
    statusOfDay: 'car',
    weekNumber: 13,
  },
  {
    date: '01-04-21',
    durationTrip: '0:35',
    meansOfTransport: 'car',
    routeTripFrom: 'Terneuzen - Vlissingen',
    routeTripTo: 'Terneuzen - Vlissingen',
    statusOfDay: 'car',
    weekNumber: 13,
  },
  {
    date: '01-04-21',
    durationTrip: '1:45',
    meansOfTransport: 'car',
    routeTripFrom: 'Vlissingen - Tilburg',
    routeTripTo: 'Vlissingen - Tilburg',
    statusOfDay: 'car',
    weekNumber: 13,
  },
  {
    date: '02-04-21',
    durationTrip: '2:30',
    meansOfTransport: 'public',
    routeTripFrom: 'Tilburg - Vlissingen',
    routeTripTo: 'Tilburg - Vlissingen',
    statusOfDay: 'public',
    weekNumber: 13,
  },
  {
    date: '02-04-21',
    durationTrip: '2:35',
    meansOfTransport: 'public',
    routeTripFrom: 'Vlissingen - Tilburg',
    routeTripTo: 'Vlissingen - Tilburg',
    statusOfDay: 'public',
    weekNumber: 13,
  },
  {
    date: '05-04-21',
    durationTrip: '0:00',
    meansOfTransport: 'day off',
    routeTripFrom: '',
    routeTripTo: '',
    statusOfDay: 'day off',
    weekNumber: 14,
  },
  {
    date: '06-04-21',
    durationTrip: '2:30',
    meansOfTransport: 'public',
    routeTripFrom: 'Tilburg - Vlissingen',
    routeTripTo: 'Tilburg - Vlissingen',
    statusOfDay: 'public',
    weekNumber: 14,
  },
  {
    date: '06-04-21',
    durationTrip: '2:35',
    meansOfTransport: 'public',
    routeTripFrom: 'Vlissingen - Tilburg',
    routeTripTo: 'Vlissingen - Tilburg',
    statusOfDay: 'public',
    weekNumber: 14,
  },
  {
    date: '07-04-21',
    durationTrip: '1:35',
    meansOfTransport: 'car',
    routeTripFrom: 'Tilburg - Vlissingen',
    routeTripTo: 'Tilburg - Vlissingen',
    statusOfDay: 'car',
    weekNumber: 14,
  },
  {
    date: '07-04-21',
    durationTrip: '0:35',
    meansOfTransport: 'car',
    routeTripFrom: 'Vlissingen - Terneuzen',
    routeTripTo: 'Vlissingen - Terneuzen',
    statusOfDay: 'car',
    weekNumber: 14,
  },
  {
    date: '08-04-21',
    durationTrip: '0:35',
    meansOfTransport: 'car',
    routeTripFrom: 'Terneuzen - Vlissingen',
    routeTripTo: 'Terneuzen - Vlissingen',
    statusOfDay: 'car',
    weekNumber: 14,
  },
  {
    date: '08-04-21',
    durationTrip: '0:35',
    meansOfTransport: 'car',
    routeTripFrom: 'Vlissingen - Terneuzen',
    routeTripTo: 'Vlissingen - Terneuzen',
    statusOfDay: 'car',
    weekNumber: 14,
  },
  {
    date: 09 - 04 - 21,
    statusOfDay: 'home',
    weekNumber: 14,
  },
];
