const logData = [
  {
    date: '31-03-21',
    durationTrip: 35,
    meansOfTransport: 'car',
    routeTripFrom: 'Terneuzen',
    routeTripTo: 'Vlissingen',
    statusOfDay: 'working at the office',
    weekNumber: 13,
  },
  {
    date: '31-03-21',
    durationTrip: 35,
    meansOfTransport: 'car',
    routeTripFrom: 'Vlissingen',
    routeTripTo: 'Terneuzen',
    statusOfDay: 'working at the office',
    weekNumber: 13,
  },
  {
    date: '01-04-21',
    durationTrip: 35,
    meansOfTransport: 'car',
    routeTripFrom: 'Terneuzen',
    routeTripTo: 'Vlissingen',
    statusOfDay: 'working at the office',
    weekNumber: 13,
  },
  {
    date: '01-04-21',
    durationTrip: 105,
    meansOfTransport: 'car',
    routeTripFrom: 'Vlissingen',
    routeTripTo: 'Tilburg',
    statusOfDay: 'working at the office',
    weekNumber: 13,
  },
  {
    date: '02-04-21',
    durationTrip: 150,
    meansOfTransport: 'public',
    routeTripFrom: 'Tilburg',
    routeTripTo: 'Vlissingen',
    statusOfDay: 'working at the office',
    weekNumber: 13,
  },
  {
    date: '02-04-21',
    durationTrip: 155,
    meansOfTransport: 'public',
    routeTripFrom: 'Vlissingen',
    routeTripTo: 'Tilburg',
    statusOfDay: 'working at the office',
    weekNumber: 13,
  },
  {
    date: '05-04-21',
    statusOfDay: 'day off',
    weekNumber: 14,
  },
  {
    date: '06-04-21',
    durationTrip: 150,
    meansOfTransport: 'public',
    routeTripFrom: 'Tilburg',
    routeTripTo: 'Vlissingen',
    statusOfDay: 'working at the office',
    weekNumber: 14,
  },
  {
    date: '06-04-21',
    durationTrip: 155,
    meansOfTransport: 'public',
    routeTripFrom: 'Vlissingen',
    routeTripTo: 'Tilburg',
    statusOfDay: 'working at the office',
    weekNumber: 14,
  },
  {
    date: '07-04-21',
    durationTrip: 95,
    meansOfTransport: 'car',
    routeTripFrom: 'Tilburg',
    routeTripTo: 'Vlissingen',
    statusOfDay: 'working at the office',
    weekNumber: 14,
  },
  {
    date: '07-04-21',
    durationTrip: 35,
    meansOfTransport: 'car',
    routeTripFrom: 'Vlissingen',
    routeTripTo: 'Terneuzen',
    statusOfDay: 'working at the office',
    weekNumber: 14,
  },
  {
    date: '08-04-21',
    durationTrip: 35,
    meansOfTransport: 'car',
    routeTripFrom: 'Terneuzen',
    routeTripTo: 'Vlissingen',
    statusOfDay: 'working at the office',
    weekNumber: 14,
  },
  {
    date: '08-04-21',
    durationTrip: 35,
    meansOfTransport: 'car',
    routeTripFrom: 'Vlissingen',
    routeTripTo: 'Terneuzen',
    statusOfDay: 'working at the office',
    weekNumber: 14,
  },
  {
    date: '09-04-21',
    statusOfDay: 'home',
    weekNumber: 14,
  },
];
